In [58]:
import pandas as pd

In [59]:
distance_matrix = pd.read_csv(
    'AutoIRAD-dataset-distances.csv', index_col=0)
distance_matrix

monks-2.dat  rabe_131.csv  contrac_R.dat  \
monks-2.dat                            0.000000      0.627923       0.455466   
rabe_131.csv                           0.627923      0.000000       0.577918   
contrac_R.dat                          0.455466      0.577918       0.000000   
conn-bench-vowel-deterding.dat         0.092033      0.650764       0.467390   
conn-bench-sonar-mines-rocks_R.dat     1.014555      0.997661       0.814052   
...                                         ...           ...            ...   
schlvote.csv                           0.483285      0.837774       0.593287   
cardiotocography-3clases_R.dat         0.221889      0.680785       0.466447   
car_R.dat                              0.206337      0.627421       0.356352   
pittsburg-bridges-T-OR-D_R.dat         0.340085      0.583447       0.470556   
mfeat-morphological.csv                0.271278      0.747974       0.564495   

                                    conn-bench-vowel-deterding.dat  \
monks-2.dat                                               0.092033   
rabe_131.csv                                              0.650764   
contrac_R.dat                                             0.467390   
conn-bench-vowel-deterding.dat                            0.000000   
conn-bench-sonar-mines-rocks_R.dat                        1.033600   
...                                                            ...   
schlvote.csv                                              0.479333   
cardiotocography-3clases_R.dat                            0.224947   
car_R.dat                                                 0.218815   
pittsburg-bridges-T-OR-D_R.dat                            0.357943   
mfeat-morphological.csv                                   0.262052   

                                    conn-bench-sonar-mines-rocks_R.dat  \
monks-2.dat                                                   1.014555   
rabe_131.csv                                                  0.997661   
contrac_R.dat                                                 0.814052   
conn-bench-vowel-deterding.dat                                1.033600   
conn-bench-sonar-mines-rocks_R.dat                            0.000000   
...                                                                ...   
schlvote.csv                                                  1.093500   
cardiotocography-3clases_R.dat                                0.969117   
car_R.dat                                                     0.960254   
pittsburg-bridges-T-OR-D_R.dat                                0.978013   
mfeat-morphological.csv                                       1.012198   

                                    hepatitis_R.dat  low-res-spect_R.dat  \
monks-2.dat                                0.379417             0.193740   
rabe_131.csv                               0.523115             0.595663   
contrac_R.dat                              0.406350             0.511681   
conn-bench-vowel-deterding.dat             0.426256             0.212445   
conn-bench-sonar-mines-rocks_R.dat         0.975751             1.042188   
...                                             ...                  ...   
schlvote.csv                               0.574874             0.539357   
cardiotocography-3clases_R.dat             0.518411             0.300497   
car_R.dat                                  0.329267             0.286047   
pittsburg-bridges-T-OR-D_R.dat             0.334432             0.364612   
mfeat-morphological.csv                    0.495786             0.345352   

                                    cardiotocography-10clases_R.dat  \
monks-2.dat                                                0.329588   
rabe_131.csv                                               0.626955   
contrac_R.dat                                              0.353217   
conn-bench-vowel-deterding.dat                             0.342974   
conn-bench-sonar-mines-rocks_R.dat                         0.863258   
...   

In [60]:
n = 10

### K-Medoids

In [61]:
from sklearn_extra.cluster import KMedoids

clustering = KMedoids(n_clusters=n, metric='precomputed')
labels = clustering.fit_predict(distance_matrix)
labels

array([5, 0, 4, 9, 3, 5, 5, 1, 2, 2, 3, 8, 8, 1, 5, 9, 4, 5, 5, 8, 4, 9,
       8, 4, 4, 4, 9, 9, 5, 5, 3, 8, 5, 2, 9, 4, 1, 6, 4, 8, 5, 1, 2, 5,
       4, 5, 5, 5, 0, 2, 8, 5, 6, 6, 8, 2, 0, 6, 8, 4, 3, 3, 9, 3, 8, 4,
       8, 6, 2, 9, 5, 6, 3, 9, 5, 1, 5, 2, 3, 8, 8, 6, 5, 9, 3, 3, 5, 4,
       9, 6, 5, 4, 2, 6, 1, 3, 1, 8, 8, 2, 5, 3, 7, 4, 4, 3, 8, 5, 2, 8,
       0, 1, 7, 4, 3, 8, 9, 9, 9, 8, 0, 5, 6, 5, 6, 1, 6, 5, 9])

In [62]:
for i in range(n):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['rabe_131.csv', 'energy-y1_R.dat', 'image-segmentation.dat',
       'audiology-std.dat', 'energy-y2_R.dat'],
      dtype='object')
Cluster 1:
Index(['cardiotocography-10clases_R.dat', 'ionosphere_R.dat', 'spectf.dat',
       'yeast_R.dat', 'breast-cancer-wisc-diag_R.dat', 'dermatology_R.dat',
       'pittsburg-bridges-SPAN_R.dat', 'breast-cancer-wisc_R.dat',
       'cardiotocography-3clases_R.dat'],
      dtype='object')
Cluster 2:
Index(['acute-nephritis.dat', 'pittsburg-bridges-TYPE_R.dat',
       'heart-hungarian_R.dat', 'vertebral-column-2clases_R.dat',
       'vertebral-column-3clases_R.dat', 'glass_R.dat', 'breast-cancer_R.dat',
       'wine_R.dat', 'seeds_R.dat', 'iris_R.dat', 'tic-tac-toe_R.dat'],
      dtype='object')
Cluster 3:
Index(['conn-bench-sonar-mines-rocks_R.dat', 'plant-margin_R.dat',
       'synthetic-control_R.dat', 'plant-texture_R.dat', 'libras_R.dat',
       'plant-shape_R.dat', 'molec-biol-splice_R.dat', 'musk-1_R.dat',
       'steel-plates_R.

### AHC

In [63]:
from sklearn.cluster import AgglomerativeClustering

clustering = AgglomerativeClustering(
    n_clusters=n, metric='precomputed', linkage='complete')
labels = clustering.fit_predict(distance_matrix)
labels

array([3, 0, 2, 3, 2, 3, 3, 3, 2, 2, 2, 1, 1, 3, 3, 3, 0, 3, 3, 0, 7, 3,
       0, 1, 3, 0, 3, 3, 3, 3, 2, 0, 3, 2, 3, 3, 3, 3, 7, 1, 3, 3, 2, 3,
       7, 3, 3, 3, 3, 2, 5, 3, 3, 3, 9, 2, 3, 3, 1, 3, 2, 2, 3, 2, 1, 3,
       6, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 2, 2, 4, 1, 3, 3, 3, 2, 2, 3, 3,
       3, 3, 3, 3, 2, 3, 3, 2, 3, 1, 3, 2, 3, 2, 3, 7, 2, 2, 8, 3, 2, 0,
       3, 3, 3, 3, 2, 0, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [64]:
for i in range(n):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['rabe_131.csv', 'lupus.csv', 'sleuth_case2002.csv', 'chatfield_4.csv',
       'diggle_table_a2.csv', 'chscase_vine1.csv', 'transplant.csv',
       'bodyfat.csv'],
      dtype='object')
Cluster 1:
Index(['teachingAssistant.csv', 'analcatdata_lawsuit.csv',
       'rmftsa_sleepdata.csv', 'lowbwt.csv', 'disclosure_z.csv',
       'diabetes.csv', 'prnn_synth.csv', 'veteran.csv', 'tae.csv'],
      dtype='object')
Cluster 2:
Index(['contrac_R.dat', 'conn-bench-sonar-mines-rocks_R.dat',
       'acute-nephritis.dat', 'pittsburg-bridges-TYPE_R.dat',
       'plant-margin_R.dat', 'synthetic-control_R.dat',
       'heart-hungarian_R.dat', 'vertebral-column-2clases_R.dat',
       'vertebral-column-3clases_R.dat', 'glass_R.dat', 'plant-texture_R.dat',
       'libras_R.dat', 'plant-shape_R.dat', 'breast-cancer_R.dat',
       'molec-biol-splice_R.dat', 'wine_R.dat', 'musk-1_R.dat',
       'steel-plates_R.dat', 'ecoli_R.dat', 'seeds_R.dat', 'spambase_R.dat',
       'iris_R.dat', 'molec-

### DBSCAN

In [65]:
from sklearn.cluster import DBSCAN

clustering = DBSCAN(eps=0.2, min_samples=2, metric='precomputed')
labels = clustering.fit_predict(distance_matrix)
labels

array([ 0, -1, -1,  0, -1, -1,  0, -1, -1, -1,  1,  2, -1, -1,  0,  0, -1,
       -1, -1, -1, -1,  0, -1, -1, -1, -1,  0,  0,  0,  0,  1, -1,  0,  3,
        0, -1, -1,  0,  4, -1, -1,  0,  3,  0,  4,  5, -1,  5,  0, -1, -1,
       -1,  0,  0, -1,  6, -1,  0, -1, -1,  1, -1,  0,  1, -1,  7, -1,  0,
        3,  0,  0,  0,  1,  0, -1,  0,  0, -1, -1, -1, -1,  0, -1,  0,  1,
        1,  0, -1,  0,  0,  0,  7,  6,  0, -1,  8, -1, -1, -1,  6,  0, -1,
        0,  4,  8, -1, -1,  0,  3, -1, -1,  0,  0,  7, -1, -1,  0,  0,  0,
        2,  0,  0,  0, -1, -1,  0,  0, -1, -1])

In [66]:
for i in range(labels.max() + 1):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['monks-2.dat', 'conn-bench-vowel-deterding.dat', 'low-res-spect_R.dat',
       'flags_R.dat', 'statlog-australian-credit_R.dat',
       'waveform-noise_R.dat', 'semeion_R.dat',
       'oocytes_merluccius_nucleus_4d.dat', 'statlog-heart_R.dat',
       'heart-cleveland_R.dat', 'cylinder-bands_R.dat', 'bank_R.dat',
       'titanic_R.dat', 'yeast_R.dat', 'planning_R.dat', 'energy-y1_R.dat',
       'wine-quality-red_R.dat', 'wall-following_R.dat', 'chess-krvkp_R.dat',
       'abalone_R.dat', 'pima_R.dat', 'statlog-image_R.dat',
       'haberman-survival_R.dat', 'blood_R.dat', 'ozone_R.dat',
       'breast-cancer-wisc-diag_R.dat', 'statlog-german-credit_R.dat',
       'wine-quality-white_R.dat', 'monks-3.dat', 'ilpd-indian-liver_R.dat',
       'waveform_R.dat', 'statlog-vehicle_R.dat', 'heart-va_R.dat',
       'led-display_R.dat', 'echocardiogram_R.dat', 'hayes-roth.dat',
       'congressional-voting_R.dat', 'breast-cancer-wisc_R.dat',
       'oocytes_trisopterus_nucleus_2f

In [67]:
distance_matrix = pd.read_csv(
    'AutoIRAD-dataset-distances-ohe.csv', index_col=0)
distance_matrix

monks-2.dat  rabe_131.csv  contrac_R.dat  \
monks-2.dat                            0.000000      0.627923       0.455466   
rabe_131.csv                           0.627923      0.000000       0.577918   
contrac_R.dat                          0.455466      0.577918       0.000000   
conn-bench-vowel-deterding.dat         0.092033      0.650764       0.467390   
conn-bench-sonar-mines-rocks_R.dat     1.014555      0.997661       0.814052   
...                                         ...           ...            ...   
analcatdata_boxing1.csv                0.619122      0.547262       0.790376   
car_R.dat                              0.206337      0.627421       0.356352   
pittsburg-bridges-T-OR-D_R.dat         0.340085      0.583447       0.470556   
labor.csv                              1.582688      1.357900       1.635620   
mfeat-morphological.csv                0.271278      0.747974       0.564495   

                                    conn-bench-vowel-deterding.dat  \
monks-2.dat                                               0.092033   
rabe_131.csv                                              0.650764   
contrac_R.dat                                             0.467390   
conn-bench-vowel-deterding.dat                            0.000000   
conn-bench-sonar-mines-rocks_R.dat                        1.033600   
...                                                            ...   
analcatdata_boxing1.csv                                   0.714860   
car_R.dat                                                 0.218815   
pittsburg-bridges-T-OR-D_R.dat                            0.357943   
labor.csv                                                 1.625509   
mfeat-morphological.csv                                   0.262052   

                                    conn-bench-sonar-mines-rocks_R.dat  \
monks-2.dat                                                   1.014555   
rabe_131.csv                                                  0.997661   
contrac_R.dat                                                 0.814052   
conn-bench-vowel-deterding.dat                                1.033600   
conn-bench-sonar-mines-rocks_R.dat                            0.000000   
...                                                                ...   
analcatdata_boxing1.csv                                       1.160889   
car_R.dat                                                     0.960254   
pittsburg-bridges-T-OR-D_R.dat                                0.978013   
labor.csv                                                     1.601812   
mfeat-morphological.csv                                       1.012198   

                                    hepatitis_R.dat  low-res-spect_R.dat  \
monks-2.dat                                0.379417             0.193740   
rabe_131.csv                               0.523115             0.595663   
contrac_R.dat                              0.406350             0.511681   
conn-bench-vowel-deterding.dat             0.426256             0.212449   
conn-bench-sonar-mines-rocks_R.dat         0.975751             1.042194   
...                                             ...                  ...   
analcatdata_boxing1.csv                    0.667203             0.666802   
car_R.dat                                  0.329267             0.286047   
pittsburg-bridges-T-OR-D_R.dat             0.334432             0.364612   
labor.csv                                  1.560471             1.579872   
mfeat-morphological.csv                    0.495786             0.345352   

                                    cardiotocography-10clases_R.dat  \
monks-2.dat                                                0.329588   
rabe_131.csv                                               0.626955   
contrac_R.dat                                              0.353217   
conn-bench-vowel-deterding.dat                             0.342974   
conn-bench-sonar-mines-rocks_R.dat                         0.863258   
...   

In [68]:
from sklearn_extra.cluster import KMedoids

clustering = KMedoids(n_clusters=n, metric='precomputed')
labels = clustering.fit_predict(distance_matrix)
labels

array([0, 4, 4, 5, 7, 9, 0, 3, 6, 4, 1, 1, 7, 1, 1, 2, 0, 5, 4, 1, 0, 9,
       1, 6, 1, 5, 1, 1, 6, 4, 4, 6, 5, 5, 0, 0, 7, 1, 1, 0, 6, 3, 5, 4,
       3, 2, 6, 9, 0, 3, 6, 4, 0, 6, 1, 0, 9, 0, 1, 3, 7, 1, 9, 2, 5, 1,
       7, 9, 2, 1, 4, 7, 7, 5, 7, 1, 4, 1, 8, 4, 1, 5, 1, 0, 2, 7, 5, 9,
       9, 2, 0, 7, 7, 1, 1, 2, 0, 5, 7, 7, 0, 4, 5, 8, 0, 4, 7, 8, 2, 6,
       3, 1, 9, 7, 4, 2, 7, 9, 6, 6, 7, 1, 0, 6, 1, 2, 9, 2, 4, 2, 8, 4,
       7, 1, 5, 5, 5, 1, 2, 0, 2, 9, 5, 1, 3, 9, 8, 9, 1, 5])

In [69]:
for i in range(n):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['monks-2.dat', 'low-res-spect_R.dat', 'flags_R.dat', 'parkinsons_R.dat',
       'statlog-heart_R.dat', 'heart-cleveland_R.dat', 'cylinder-bands_R.dat',
       'breast-cancer-wisc-prog_R.dat', 'planning_R.dat', 'no2.csv',
       'pm10.csv', 'haberman-survival_R.dat', 'statlog-german-credit_R.dat',
       'teaching_R.dat', 'ilpd-indian-liver_R.dat', 'heart-va_R.dat',
       'congressional-voting_R.dat', 'spect.dat'],
      dtype='object')
Cluster 1:
Index(['squash-unstored.csv', 'braziltourism.csv', 'teachingAssistant.csv',
       'analcatdata_lawsuit.csv', 'solar-flare.csv', 'sleuth_case2002.csv',
       'visualizing_livestock.csv', 'chatfield_4.csv', 'cloud.csv',
       'chscase_vine1.csv', 'white-clover.csv', 'squash-stored.csv',
       'plasma_retinol.csv', 'annealing.dat', 'fri_c0_250_5.csv',
       'disclosure_z.csv', 'diabetes.csv', 'lung-cancer_R.dat',
       'newton_hema.csv', 'analcatdata_germangss.csv', 'mfeat-karhunen.csv',
       'prnn_synth.csv', 'veteran.

In [70]:
from sklearn.cluster import AgglomerativeClustering

clustering = AgglomerativeClustering(
    n_clusters=n, metric='precomputed', linkage='complete')
labels = clustering.fit_predict(distance_matrix)
labels

array([5, 4, 5, 5, 1, 5, 5, 5, 1, 1, 3, 3, 1, 3, 4, 5, 5, 5, 4, 9, 5, 5,
       4, 0, 2, 5, 4, 3, 0, 0, 1, 4, 5, 5, 5, 5, 1, 4, 2, 5, 1, 0, 5, 5,
       5, 5, 0, 0, 5, 5, 1, 0, 5, 0, 3, 5, 5, 5, 3, 5, 1, 0, 5, 5, 5, 9,
       1, 5, 5, 3, 1, 1, 1, 5, 1, 3, 5, 1, 5, 1, 0, 5, 7, 5, 5, 1, 5, 5,
       5, 5, 5, 1, 1, 8, 3, 5, 5, 5, 1, 1, 5, 5, 5, 5, 5, 5, 1, 5, 5, 1,
       1, 3, 5, 1, 5, 5, 1, 5, 0, 1, 1, 3, 5, 1, 4, 5, 5, 5, 0, 5, 5, 5,
       1, 4, 5, 5, 5, 3, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 6, 5])

In [71]:
for i in range(n):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['horse-colic.dat', 'socmob.csv', 'rmftsa_sleepdata.csv', 'kidney.csv',
       'hill-valley.dat', 'lowbwt.csv', 'autos.csv', 'ar4.csv',
       'annealing.dat', 'newton_hema.csv', 'kc3.csv', 'meta.csv'],
      dtype='object')
Cluster 1:
Index(['conn-bench-sonar-mines-rocks_R.dat', 'acute-nephritis.dat',
       'pittsburg-bridges-TYPE_R.dat', 'plant-margin_R.dat',
       'pittsburg-bridges-MATERIAL_R.dat', 'synthetic-control_R.dat',
       'heart-hungarian_R.dat', 'vertebral-column-2clases_R.dat',
       'vertebral-column-3clases_R.dat', 'glass_R.dat',
       'pittsburg-bridges-REL-L_R.dat', 'plant-texture_R.dat', 'libras_R.dat',
       'plant-shape_R.dat', 'lung-cancer_R.dat', 'breast-cancer_R.dat',
       'molec-biol-splice_R.dat', 'wine_R.dat', 'musk-1_R.dat',
       'steel-plates_R.dat', 'ecoli_R.dat', 'seeds_R.dat', 'spambase_R.dat',
       'pittsburg-bridges-SPAN_R.dat', 'iris_R.dat',
       'molec-biol-promoter_R.dat', 'mushroom_R.dat', 'elusage.csv',
       'tic-

In [72]:
from sklearn.cluster import DBSCAN

clustering = DBSCAN(eps=0.2, min_samples=2, metric='precomputed')
labels = clustering.fit_predict(distance_matrix)
labels

array([ 0, -1, -1,  0, -1, -1,  0, -1, -1, -1, -1, -1,  1,  2, -1, -1,  0,
        0, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1,  0,  0,
        0,  0,  1, -1, -1,  0,  3, -1,  0, -1, -1,  0,  4, -1, -1,  0,  3,
       -1,  0,  4, -1,  5, -1,  5, -1,  0, -1, -1, -1,  0,  0, -1,  6, -1,
        0, -1, -1,  1, -1,  0,  1, -1,  7, -1,  0,  3, -1,  0, -1,  0,  0,
        1,  0, -1, -1,  0,  0, -1, -1, -1, -1,  0, -1,  0,  1,  1,  0, -1,
        0,  0,  0,  7,  6,  0, -1,  8, -1, -1, -1,  6,  7,  0, -1,  0,  4,
        8, -1, -1,  0,  3, -1, -1, -1,  0, -1,  0,  0,  7, -1, -1,  0,  0,
        0,  2,  0,  0,  0, -1, -1, -1,  0, -1,  0, -1, -1, -1])

In [73]:
for i in range(labels.max() + 1):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['monks-2.dat', 'conn-bench-vowel-deterding.dat', 'low-res-spect_R.dat',
       'flags_R.dat', 'statlog-australian-credit_R.dat',
       'waveform-noise_R.dat', 'semeion_R.dat',
       'oocytes_merluccius_nucleus_4d.dat', 'statlog-heart_R.dat',
       'heart-cleveland_R.dat', 'cylinder-bands_R.dat', 'bank_R.dat',
       'titanic_R.dat', 'yeast_R.dat', 'planning_R.dat', 'energy-y1_R.dat',
       'wine-quality-red_R.dat', 'wall-following_R.dat', 'chess-krvkp_R.dat',
       'abalone_R.dat', 'pima_R.dat', 'statlog-image_R.dat',
       'haberman-survival_R.dat', 'blood_R.dat', 'ozone_R.dat',
       'breast-cancer-wisc-diag_R.dat', 'statlog-german-credit_R.dat',
       'wine-quality-white_R.dat', 'monks-3.dat', 'ilpd-indian-liver_R.dat',
       'waveform_R.dat', 'statlog-vehicle_R.dat', 'heart-va_R.dat',
       'led-display_R.dat', 'echocardiogram_R.dat', 'hayes-roth.dat',
       'congressional-voting_R.dat', 'schizo.csv', 'breast-cancer-wisc_R.dat',
       'oocytes_trisopte