In [19]:
import pandas as pd

In [20]:
distance_matrix = pd.read_csv('AutoIRAD-dataset-distances.csv', index_col=0)
distance_matrix

blood_R.dat.dvc  \
blood_R.dat.dvc                             0.000000   
acute-inflammation_R.dat.dvc                0.627923   
monks-2.dat                                 0.455466   
rabe_131.csv                                0.092033   
squash-unstored.csv.dvc                     1.014555   
...                                              ...   
abalone_R.dat                               0.483285   
wine_R.dat.dvc                              0.221889   
plant-shape_R.dat                           0.206337   
cardiotocography-10clases_R.dat.dvc         0.340085   
spambase_R.dat.dvc                          0.271278   

                                     acute-inflammation_R.dat.dvc  \
blood_R.dat.dvc                                          0.627923   
acute-inflammation_R.dat.dvc                             0.000000   
monks-2.dat                                              0.577918   
rabe_131.csv                                             0.650764   
squash-unstored.csv.dvc                                  0.997661   
...                                                           ...   
abalone_R.dat                                            0.837774   
wine_R.dat.dvc                                           0.680785   
plant-shape_R.dat                                        0.627421   
cardiotocography-10clases_R.dat.dvc                      0.583447   
spambase_R.dat.dvc                                       0.747974   

                                     monks-2.dat  rabe_131.csv  \
blood_R.dat.dvc                         0.455466      0.092033   
acute-inflammation_R.dat.dvc            0.577918      0.650764   
monks-2.dat                             0.000000      0.467390   
rabe_131.csv                            0.467390      0.000000   
squash-unstored.csv.dvc                 0.814052      1.033600   
...                                          ...           ...   
abalone_R.dat                           0.593287      0.479333   
wine_R.dat.dvc                          0.466447      0.224947   
plant-shape_R.dat                       0.356352      0.218815   
cardiotocography-10clases_R.dat.dvc     0.470556      0.357943   
spambase_R.dat.dvc                      0.564495      0.262052   

                                     squash-unstored.csv.dvc  \
blood_R.dat.dvc                                     1.014555   
acute-inflammation_R.dat.dvc                        0.997661   
monks-2.dat                                         0.814052   
rabe_131.csv                                        1.033600   
squash-unstored.csv.dvc                             0.000000   
...                                                      ...   
abalone_R.dat                                       1.093500   
wine_R.dat.dvc                                      0.969117   
plant-shape_R.dat                                   0.960254   
cardiotocography-10clases_R.dat.dvc                 0.978013   
spambase_R.dat.dvc                                  1.012198   

                                     fri_c0_250_5.csv.dvc  \
blood_R.dat.dvc                                  0.379417   
acute-inflammation_R.dat.dvc                     0.523115   
monks-2.dat                                      0.406350   
rabe_131.csv                                     0.426256   
squash-unstored.csv.dvc                          0.975751   
...                                                   ...   
abalone_R.dat                                    0.574874   
wine_R.dat.dvc                                   0.518411   
plant-shape_R.dat                                0.329267   
cardiotocography-10clases_R.dat.dvc              0.334432   
spambase_R.dat.dvc                               0.495786   

                                     image-segmentation.dat.dvc  \
blood_R.dat.dvc                                        0.193740   
acute-inflammation_R.dat.dvc                           0.595663   
monks-2.dat                            

### K-Medoids

In [21]:
from sklearn_extra.cluster import KMedoids

clustering = KMedoids(n_clusters=9, metric='precomputed')
labels = clustering.fit_predict(distance_matrix)
labels

array([5, 0, 4, 5, 3, 5, 5, 1, 2, 2, 3, 8, 8, 1, 5, 5, 4, 5, 5, 8, 4, 6,
       8, 4, 4, 4, 5, 5, 5, 5, 3, 8, 5, 2, 5, 4, 1, 6, 4, 8, 5, 1, 2, 5,
       4, 5, 5, 5, 0, 2, 8, 5, 6, 6, 8, 2, 0, 6, 8, 4, 3, 3, 5, 3, 8, 4,
       8, 6, 2, 5, 5, 6, 3, 5, 5, 1, 5, 2, 3, 8, 8, 6, 5, 5, 3, 3, 5, 4,
       5, 6, 5, 4, 2, 6, 1, 3, 1, 8, 8, 2, 5, 3, 7, 4, 4, 3, 8, 5, 2, 8,
       0, 1, 7, 4, 3, 8, 5, 5, 5, 8, 0, 5, 6, 5, 6, 1, 6, 5, 5])

In [22]:
for i in range(9):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['acute-inflammation_R.dat.dvc', 'waveform-noise_R.dat',
       'rmftsa_sleepdata.csv', 'glass_R.dat.dvc',
       'pittsburg-bridges-REL-L_R.dat'],
      dtype='object')
Cluster 1:
Index(['bodyfat.csv.dvc', 'conn-bench-sonar-mines-rocks_R.dat',
       'energy-y2_R.dat.dvc', 'zoo_R.dat', 'bank_R.dat.dvc', 'planning_R.dat',
       'statlog-australian-credit_R.dat.dvc',
       'breast-cancer-wisc-diag_R.dat.dvc', 'wine_R.dat.dvc'],
      dtype='object')
Cluster 2:
Index(['prnn_synth.csv.dvc', 'spect.dat.dvc', 'fertility_R.dat.dvc',
       'planning_R.dat.dvc', 'schizo.csv.dvc', 'sleuth_case2002.csv.dvc',
       'heart-hungarian_R.dat', 'analcatdata_lawsuit.csv.dvc',
       'newton_hema.csv.dvc', 'no2.csv', 'annealing.dat'],
      dtype='object')
Cluster 3:
Index(['squash-unstored.csv.dvc', 'statlog-german-credit_R.dat.dvc',
       'pm10.csv.dvc', 'oocytes_merluccius_nucleus_4d.dat',
       'ionosphere_R.dat.dvc', 'heart-cleveland_R.dat',
       'statlog-image_R.dat.dvc', 

### AHC

In [23]:
from sklearn.cluster import AgglomerativeClustering

clustering = AgglomerativeClustering(
    n_clusters=9, metric='precomputed', linkage='complete')
labels = clustering.fit_predict(distance_matrix)
labels

array([8, 1, 2, 8, 2, 8, 8, 8, 2, 2, 2, 3, 3, 8, 8, 8, 1, 8, 8, 1, 7, 8,
       1, 3, 8, 1, 8, 8, 8, 8, 2, 1, 8, 2, 8, 8, 8, 8, 7, 3, 8, 8, 2, 8,
       7, 8, 8, 8, 8, 2, 5, 8, 8, 8, 0, 2, 8, 8, 3, 8, 2, 2, 8, 2, 3, 8,
       6, 8, 2, 8, 8, 8, 2, 8, 8, 8, 8, 2, 2, 4, 3, 8, 8, 8, 2, 2, 8, 8,
       8, 8, 8, 8, 2, 8, 8, 2, 8, 3, 8, 2, 8, 2, 8, 7, 2, 2, 0, 8, 2, 1,
       8, 8, 8, 8, 2, 1, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [24]:
for i in range(9):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['socmob.csv', 'vertebral-column-3clases_R.dat'], dtype='object')
Cluster 1:
Index(['acute-inflammation_R.dat.dvc', 'visualizing_livestock.csv.dvc',
       'tae.csv.dvc', 'mushroom_R.dat.dvc', 'acute-nephritis.dat',
       'post-operative_R.dat.dvc', 'arrhythmia_R.dat', 'teaching_R.dat.dvc'],
      dtype='object')
Cluster 2:
Index(['monks-2.dat', 'squash-unstored.csv.dvc', 'prnn_synth.csv.dvc',
       'spect.dat.dvc', 'statlog-german-credit_R.dat.dvc', 'pm10.csv.dvc',
       'fertility_R.dat.dvc', 'planning_R.dat.dvc', 'schizo.csv.dvc',
       'sleuth_case2002.csv.dvc', 'oocytes_merluccius_nucleus_4d.dat',
       'ionosphere_R.dat.dvc', 'heart-cleveland_R.dat',
       'heart-hungarian_R.dat', 'statlog-image_R.dat.dvc',
       'analcatdata_lawsuit.csv.dvc', 'spectf.dat', 'yeast_R.dat',
       'vertebral-column-2clases_R.dat', 'newton_hema.csv.dvc', 'ar4.csv',
       'no2.csv', 'plasma_retinol.csv', 'energy-y1_R.dat', 'soybean.dat.dvc',
       'annealing.dat', 'pittsburg

### DBSCAN

In [25]:
from sklearn.cluster import DBSCAN

clustering = DBSCAN(eps=0.5, min_samples=2, metric='precomputed')
labels = clustering.fit_predict(distance_matrix)
labels

array([ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  0,  0,  0,  0,
        0,  0, -1,  3,  0, -1,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,
        0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0, -1,
        0,  0,  0, -1,  0, -1,  0,  2,  0,  0,  0,  0,  0,  2,  0, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  4,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,
        0,  3,  0,  0, -1,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [26]:
for i in range(9):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['blood_R.dat.dvc', 'monks-2.dat', 'rabe_131.csv',
       'squash-unstored.csv.dvc', 'fri_c0_250_5.csv.dvc',
       'image-segmentation.dat.dvc', 'bodyfat.csv.dvc', 'prnn_synth.csv.dvc',
       'spect.dat.dvc', 'statlog-german-credit_R.dat.dvc',
       ...
       'chess-krvkp_R.dat', 'pittsburg-bridges-REL-L_R.dat',
       'plant-texture_R.dat', 'libras_R.dat', 'disclosure_z.csv.dvc',
       'abalone_R.dat', 'wine_R.dat.dvc', 'plant-shape_R.dat',
       'cardiotocography-10clases_R.dat.dvc', 'spambase_R.dat.dvc'],
      dtype='object', length=105)
Cluster 1:
Index(['rabe_131.csv.dvc', 'disclosure_z.csv'], dtype='object')
Cluster 2:
Index(['conn-bench-vowel-deterding.dat', 'diggle_table_a2.csv',
       'synthetic-control_R.dat'],
      dtype='object')
Cluster 3:
Index(['cardiotocography-10clases_R.dat', 'solar-flare.csv',
       'hepatitis_R.dat.dvc', 'dermatology_R.dat.dvc'],
      dtype='object')
Cluster 4:
Index(['titanic_R.dat', 'squash-stored.csv'], dtype='object')